module.exports = {
  EMPLOY: 'EMPLOY',
  CLIENT: 'CLIENT',
  ACCOUNTANT: 'ACCOUNTANT',
  DRIVER: 'DRIVER',
  PICKER: 'PICKER',
  MOOVO_CUSTOMER: 'MOOVO_CUSTOMER',
  ZID_USER: 'ZID_USER',
  SALLA_USER: 'SALLA_USER',
};
